### ISSUE TITLE
Possible to use File class as cache store with Cachy?

### ISSUE THREAD

**Issue by cyclingzealot** [grosser/cachy#8]
Is it possible to use a File class with the cache store?  This line:
```
    121     @cache_store = wrap_cache(cache)
    122     @cache_store.write HEALTH_CHECK_KEY, 'yes'
```

causes wrong number of arguments for .write

```
/usr/local/rvm/gems/ruby-2.1.5/gems/cachy-0.4.1/lib/cachy.rb:122:in `write': wrong number of arguments (2 for 1) (ArgumentError)
	from /usr/local/rvm/gems/ruby-2.1.5/gems/cachy-0.4.1/lib/cachy.rb:122:in `cache_store='
	from ./tlaloc.rb:48:in `<main>'
```

**Comment by grosser** [comment]
File does not have a write key/value interface ... try ActiveSupport::Cache::FileStore
